### PR TITLE
fixed css and chatroom

### PR DESCRIPTION
**Pull request by Kaylee2319**

### CODE REVIEW

**Comment by eddroid** [comment]
All that CSS copy-pasting looks exhausting. 😓 

Poor Phillip. I don't know what happened to get him deleted, but I hope he's ok. 🙏 

`Chats` should probably render little `Chat` components.

You rarely have to type out the words `true` or `false` in code.

```js
let isSentByCurrentUser = (chat.author === currentUser.user_name);
```

`messageOutput1` and `theoutput1` aren't very good names.

**Comment by Kaylee2319** [comment]
> All that CSS copy-pasting looks exhausting. Do you know how to use sass? 😓
> no I dont know sass
> Poor Phillip. I don't know what happened to get him deleted, but I hope he's ok. 🙏
> he disappeared on use 
> `Chats` should probably render little `Chat` components.
> I set the chat up just like we learned in class
> You rarely have to type out the words `true` or `false` in code.
> ```js
> let isSentByCurrentUser = (chat.author === currentUser.user_name);
> ```
> I fixed this issue and pushed 
> `messageOutput1` and `theoutput1` aren't very good names.
> I fixed this issue and pushed

**Comment by eddroid** [comment]
Better names.
```jsx
return isSentByCurrentUser ? (
{ /* the contents of this <div> should match the other one (i.e. <Chat> component) */ }
<div className="messageMine justifyEnd">
  <img className="messagePic" src={chat.avatar} alt="user"></img>
  <div className="messageText">
    { /* <strong> is a style that should be specified in css by targeting a <span> */ }
    <strong>{chat.author}:</strong> {chat.message}
  </div>
</div>
) : (
{ /* the only difference is the class name (and that justify at the end) */ }
<div className="messageTheirs justifyStart">
  <img className="messagePic" src={chat.avatar} alt="user"></img>
  <div className="messageText">
    <strong>{chat.author}:</strong> {chat.message}
  </div>
</div>
);
```

```css
/* use descendent selectors to style different pieces of matching components */
.messageMine {
  display: flex;
  flex-direction: row-reverse;
  justify-content: flex-start;
  align-items: center;
  width: inherit;
  margin-left: 0.75rem;
}

.messageMine .messageText {
  display: flex;
  flex-direction: column;
  background-color: lightblue;
  width: inherit;
  padding: 0.5rem;
  margin-left: 5px;
  border-radius: 15px;
  font-size: 13px;
  font-family: 'Cabin', sans-serif;
}

/*
 * for the <strong> tag
 * .messageMine .messageText span { font-weight: bold; }
 */

.messageTheirs {
  display: flex;
  justify-content: flex-start;
  align-items: center;
  width: inherit;
  margin-left: 0.75rem;
}

.messageTheirs .messageText {
  display: flex;
  flex-direction: column;
  background-color: lightgreen;
  width: inherit;
  padding: 0.5rem;
  margin-left: 5px;
  border-radius: 15px;
  font-size: 13px;
  font-family: 'Cabin', sans-serif;
}

/* .messageTheirs .messageText span { font-weight: bold; } */
```

Then you can pull all the common properties out and focus on what makes them different. (DRY the CSS).

```css
/* shared message styles */
.messageText {
  display: flex;
  flex-direction: column;
  width: inherit;
  padding: 0.5rem;
  margin-left: 5px;
  border-radius: 15px;
  font-size: 13px;
  font-family: 'Cabin', sans-serif;
}

.messageMine .messageText {
  background-color: lightblue;
}

.messageTheirs .messageText {
  background-color: lightgreen;
}
```

You can try to do the same for shared properties between `messageMine` and `messageTheirs`.

I'm way pickier than a typical TA though, so they can approve if they'd like.

**Comment by Kaylee2319** [comment]
> Better names.
> 
> ```js-jsx
> return isSentByCurrentUser ? (
> { /* the contents of this <div> should match the other one (i.e. <Chat> component) */ }
> <div className="messageMine justifyEnd">
>   user</img>
>   <div className="messageText">
>     { /* <strong> is a style that should be specified in css by targeting a <span> */ }
>     <strong>{chat.author}:</strong> {chat.message}
>   </div>
> </div>
> ) : (
> { /* the only difference is the class name (and that justify at the end) */ }
> <div className="messageTheirs justifyStart">
>   user</img>
>   <div className="messageText">
>     <strong>{chat.author}:</strong> {chat.message}
>   </div>
> </div>
> );
> ```
> 
> ```css
> /* use descendent selectors to style different pieces of matching components */
> .messageMine {
>   display: flex;
>   flex-direction: row-reverse;
>   justify-content: flex-start;
>   align-items: center;
>   width: inherit;
>   margin-left: 0.75rem;
> }
> 
> .messageMine .messageText {
>   display: flex;
>   flex-direction: column;
>   background-color: lightblue;
>   width: inherit;
>   padding: 0.5rem;
>   margin-left: 5px;
>   border-radius: 15px;
>   font-size: 13px;
>   font-family: 'Cabin', sans-serif;
> }
> 
> /*
>  * for the <strong> tag
>  * .messageMine .messageText span { font-weight: bold; }
>  */
> 
> .messageTheirs {
>   display: flex;
>   justify-content: flex-start;
>   align-items: center;
>   width: inherit;
>   margin-left: 0.75rem;
> }
> 
> .messageTheirs .messageText {
>   display: flex;
>   flex-direction: column;
>   background-color: lightgreen;
>   width: inherit;
>   padding: 0.5rem;
>   margin-left: 5px;
>   border-radius: 15px;
>   font-size: 13px;
>   font-family: 'Cabin', sans-serif;
> }
> 
> /* .messageTheirs .messageText span { font-weight: bold; } */
> ```
> 
> Then you can pull all the common properties out and focus on what makes them different. (DRY the CSS).
> 
> ```css
> /* shared message styles */
> .messageText {
>   display: flex;
>   flex-direction: column;
>   width: inherit;
>   padding: 0.5rem;
>   margin-left: 5px;
>   border-radius: 15px;
>   font-size: 13px;
>   font-family: 'Cabin', sans-serif;
> }
> 
> .messageMine .messageText {
>   background-color: lightblue;
> }
> 
> .messageTheirs .messageText {
>   background-color: lightgreen;
> }
> ```
> 
> You can try to do the same for shared properties between `messageMine` and `messageTheirs`.
> 
> I'm way pickier than a typical TA though, so they can approve if they'd like.
Done!

**Review by eddroid — APPROVED** [review]
Ok. That's enough CSS learning from me today.

**Review by eddroid — APPROVED** [review]

**Pull request merged**
